# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SchoolSecurity' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SchoolSecurity

end

pod 'AMap3DMap' #3D地图
pod 'AMapSearch' #地图SDK搜索功能
pod 'AMapLocation' #定位sdk
pod 'SDWebImage'
pod 'MJRefresh'
pod 'AFNetworking', '~> 3.0'
pod 'IQKeyboardManager'
pod 'MJExtension'
pod 'SVProgressHUD'
pod 'lottie-ios' #动画